# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CpREWPZ5B0lRrfMOYSkcAYsHNq4F1NG8
"""

import os
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split
from torch.utils.data import WeightedRandomSampler
from sklearn.metrics import confusion_matrix
import flwr as fl

# load data
X, y = [], []
for file in os.listdir("C:/Users/USER/Downloads/760-FL-Parkinson-MRI-main/preprocessed_data"):
    if file.endswith(".npy"):
        label = int(file.split("_")[3])  # from e.g. ..._label_0_stripped.npy
        vol = np.load(os.path.join("C:/Users/USER/Downloads/760-FL-Parkinson-MRI-main/preprocessed_data", file))  # shape: (1, D, H, W)
        X.append(vol)
        y.append(label)

# horizontal flip along width axis (W = axis 3)
X_aug = []
y_aug = []
for i in range(len(X)):
    flipped = np.flip(X[i], axis=3)  # width flip
    X_aug.append(flipped)
    y_aug.append(y[i])

X = np.concatenate([X, np.array(X_aug)])
y = np.concatenate([y, np.array(y_aug)])

# flip vertically (height axis)
X_flip_v = [np.flip(x, axis=2) for x in X]
y_flip_v = y.copy()

# add Gaussian noise
X_noise = [x + np.random.normal(0, 0.01, x.shape) for x in X]
y_noise = y.copy()

# merge all
X = np.concatenate([X, np.array(X_flip_v), np.array(X_noise)])
y = np.concatenate([y, np.array(y_flip_v), np.array(y_noise)])

X = np.array(X)
y = np.array(y)

# normalize
X = (X - np.mean(X)) / np.std(X)

# train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# tensor
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.long)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

# sample weights
class_sample_count = np.array([np.sum(y_train == t) for t in np.unique(y_train)])
weights = 1. / class_sample_count
sample_weights = weights[y_train]  # assign weight to each sample
sampler = WeightedRandomSampler(sample_weights, len(sample_weights), replacement=True)


# dataloader
train_loader = DataLoader(
    TensorDataset(X_train_tensor, y_train_tensor),
    batch_size=2,
    sampler=sampler  # no shuffle needed
)
test_loader = DataLoader(TensorDataset(X_test_tensor, y_test_tensor), batch_size=2)

from model import Improved3DCNN  # assuming you put model class in model.py
from client import ParkinsonClient
import torch

model = Improved3DCNN()
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# Assume train_loader and test_loader are loaded already as in your original code
client = ParkinsonClient(model, train_loader, test_loader, device)
fl.client.start_numpy_client(server_address="127.0.0.1:8080", client=client)