# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CpREWPZ5B0lRrfMOYSkcAYsHNq4F1NG8
"""

import flwr as fl
import numpy as np
import torch
import copy

class DPFedAvg(fl.server.strategy.FedAvg):
    def __init__(self, noise_multiplier=0.1, clipping_norm=1.0, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.noise_multiplier = noise_multiplier
        self.clipping_norm = clipping_norm

    def aggregate_fit(self, rnd, results, failures):
        if failures:
            return None, {}

        aggregated_result, _ = super().aggregate_fit(rnd, results, failures)
        if aggregated_result is None:
            return None, {}

        # DP: Clip + noise
        weights = fl.common.parameters_to_ndarrays(aggregated_result)
        total_norm = np.linalg.norm(np.concatenate([w.flatten() for w in weights]))
        if total_norm > self.clipping_norm:
            weights = [w * (self.clipping_norm / total_norm) for w in weights]
        noisy_weights = [
            w + np.random.normal(0, self.noise_multiplier * self.clipping_norm, size=w.shape)
            for w in weights
        ]
        noisy_parameters = fl.common.ndarrays_to_parameters(noisy_weights)

        # Aggregating metrics
        total_examples = sum(fit_res.num_examples for _, fit_res in results)
        accuracy = sum(fit_res.metrics["accuracy"] * fit_res.num_examples for _, fit_res in results if "accuracy" in fit_res.metrics) / total_examples
        precision = sum(fit_res.metrics["precision"] * fit_res.num_examples for _, fit_res in results if "precision" in fit_res.metrics) / total_examples
        recall = sum(fit_res.metrics["recall"] * fit_res.num_examples for _, fit_res in results if "recall" in fit_res.metrics) / total_examples

        print(f"[Round {rnd}] Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}")

        return noisy_parameters, {
            "accuracy": accuracy,
            "precision": precision,
            "recall": recall,
        }

    def aggregate_evaluate(self, rnd, results, failures):
        if failures:
            return None, {}

        total_examples = sum(eval_res.num_examples for _, eval_res in results)
        loss = sum(eval_res.loss * eval_res.num_examples for _, eval_res in results) / total_examples
        accuracy = sum(eval_res.metrics["accuracy"] * eval_res.num_examples for _, eval_res in results if "accuracy" in eval_res.metrics) / total_examples
        precision = sum(eval_res.metrics["precision"] * eval_res.num_examples for _, eval_res in results if "precision" in eval_res.metrics) / total_examples
        recall = sum(eval_res.metrics["recall"] * eval_res.num_examples for _, eval_res in results if "recall" in eval_res.metrics) / total_examples

        print(f"[Eval {rnd}] Loss: {loss:.4f}, Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}")

        return loss, {
            "accuracy": accuracy,
            "precision": precision,
            "recall": recall,
        }


# Define a fit_config function (optional)
def fit_config(rnd: int):
    return {
        "batch_size": 2,
        "local_epochs": 1,
    }

# Start the server with DP strategy
fl.server.start_server(
    server_address="127.0.0.1:8080",
    config=fl.server.ServerConfig(num_rounds=3),
    strategy=DPFedAvg(
        noise_multiplier=0.3,  # play with this value
        clipping_norm=1.0,
        on_fit_config_fn=fit_config,
    ),
)
